Server/Controllers/ManagerController.cs
using System.Threading.Tasks;
using Application.InputModels;
using DomainModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AutoRepair.Controllers
{
    public class ManagerController : Controller
    {
        private readonly UserManager<User> _userManager;

        public ManagerController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }
        // GET
        
        
        [HttpPost]
        public async Task<IActionResult> Create(EditManagerInputModel model)
        {
            if (ModelState.IsValid)
            {
                var manager = new Manager {Email = model.Email, Firstname = model.Firstname, Lastname = model.Lastname, UserName = model.Email, Year = model.Year, OfficeId = model.OfficeId.Value};
                var result = await _userManager.CreateAsync(manager, model.Password);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                foreach (var error in result.Errors) ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }
        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            var model = new EditUserInputModel {Id = user.Id, Email = user.Email, Year = user.Year};
            return View(model);
        }
    }
}

Server/Controllers/OfficeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.InputModels;
using Application.Services;
using Application.ViewModels;
using AutoMapper;
using Domain.Services.DTO;
using DomainModel;
using DomainModel.Customers;
using DomainModel.Offices;
using DomainModel.Vehicles;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;

namespace AutoRepair.Controllers
{
    public class OfficeController : Controller
    {
        private readonly IRepository<Office,long> _officeRepository;
        private readonly IRepository<Address,long> _addressRepository;
        private readonly IRepository<Customer,long> _customerRepository;
        private readonly IRepository<Vehicle,long> _vehicleRepository;
        private readonly IRepository<Manager, string> _managerRepository;
        private readonly IOfficeControllerService _officeControllerService;

        private readonly UserManager<User> _userManager;
        private readonly IMapper _mapper;

        public OfficeController(IRepository<Office, long> officeRepository, IMapper mapper, IRepository<Address, long> addressRepository, UserManager<User> userManager, IOfficeControllerService officeControllerService, IRepository<Customer, long> customerRepository, IRepository<Vehicle, long> vehicleRepository, IRepository<Manager, string> managerRepository)
        {
            _officeRepository = officeRepository;
            _addressRepository = addressRepository;
            _userManager = userManager;
            _officeControllerService = officeControllerService;
            _customerRepository = customerRepository;
            _vehicleRepository = vehicleRepository;
            _managerRepository = managerRepository;
            _mapper = mapper;
        }

        [Route("office/{officeId}")]
        public IActionResult Edit(long officeId)
        {
            if (officeId == default)
                return View();
            var office = _officeRepository.FindById(officeId);
            //TODO здесь должна быть ViewModel а не InputModel
            var inputModel = _mapper.Map<EditOfficeInputModel>(office);
            
            var address = _addressRepository.FindById(office.AddressId);
            _mapper.Map(address, inputModel); 
            
            return View(inputModel);
        }

        [HttpPost]
        [Route("office/{officeId}")]
        public IActionResult Edit(EditOfficeInputModel model)
        {
            if (!model.IsValid())
            {
                ModelState.AddModelError("failed",
                    "Возникли ошибки при заполнении формы. Проверьте, пожалуйста, правильность и полноту заполнения.");
                return View(model);
            }

            var office = Office.Create(model.Name, model.City, model.Street, model.Home,
                model.Flat, model.Phone, model.Inn);
            _officeRepository.Add(office);
            return View(model);
        }
        
        [HttpGet("office/{officeId}/manager/edit/{managerId?}")]
        public async Task<IActionResult> EditManager(long officeId, string managerId)
        {
            var manager = _managerRepository.FindById(managerId);
            if (manager == null) return View(new EditManagerInputModel {OfficeId = officeId});
            var model = new EditManagerInputModel { Id = manager.Id, Firstname = manager.Firstname, Lastname = manager.Lastname, Password = manager.PasswordHash, OfficeId = manager.OfficeId, Email = manager.Email, Year = manager.Year};
            return View(model);
        }
        
        [HttpGet("offices")]
        public async Task<IEnumerable<OfficeSearchResult>> SearchOffices(string term)
        {
            return _officeControllerService.RetrieveOffices(term);
        }
        
        [HttpPost("office/{officeId}/manager/edit")]
        public async Task<IActionResult> EditManager(EditManagerInputModel model)
        {
            if (ModelState.IsValid)
            {
                // TODO переписать с открытого интерфейса
                // на метод Create
                model.OfficeId = 1;
                var manager = new Manager {Email = model.Email, Firstname = model.Firstname, Lastname = model.Lastname, UserName = model.Email, Year = model.Year, OfficeId = model.OfficeId.Value};
                var result = await _userManager.CreateAsync(manager, model.Password);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                foreach (var error in result.Errors) ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }
        
        // можно передавать OfficeId в модель когда на странице офиса нажимаем Регистрация Клиента
        [HttpGet("office/{officeId}/customer/edit/{customerId?}")]
        public IActionResult EditCustomer(long officeId,long? customerId)
        {
            if (customerId.HasValue)
            {
                var customer = _customerRepository.FindById(customerId.Value);
                //TODO не распознается адрес
                var vm = _mapper.Map<CustomerViewModel>(customer);
                return View(vm);
            }
            var model = new CustomerViewModel
            {
                Id = customerId,
                OfficeId = officeId
            };
            return View(model);
        }
        
        [HttpPost("office/{officeId}/customer/edit")]
        public async Task<IActionResult> EditCustomer(EditCustomerInputModel model)
        {
            if (ModelState.IsValid) 
            {
                if (model.Id == default)
                {
                    var manager = await _userManager.GetUserAsync(HttpContext.User);
                    var succeeded = _officeControllerService.RegisterNewCustomer(model, manager.Id);
                    if (succeeded) return RedirectToAction("Index", "Home");
                }

                var editSucceeded = _officeControllerService.EditCustomer(model);
                if (editSucceeded) return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError("failed",
                "Возникли ошибки при заполнении формы. Проверьте, пожалуйста, правильность и полноту заполнения.");
            
            // TODO пересмотреть подход к InputModel и ViewModel
            return View(model);
        }

        [HttpGet("office/{officeId}/request/{requestId?}")]
        public async Task<IActionResult> EditRequest(long officeId, long? requestId)
        {
            var manager = await _userManager.GetUserAsync(HttpContext.User);
            var viewModel = _officeControllerService.RetrieveRequestInitialization(officeId, requestId, manager.Id);
            //TODO заполнить View с помощью контрола https://codewithmukesh.com/blog/select2-jquery-plugin-in-aspnet-core/
            return View(viewModel);
        }
       
        [HttpGet("office/{officeId}/search/customers")]
        public async Task<IEnumerable<CustomerSearchResult>> SearchCustomers(long officeId, string term)
        {
            return _officeControllerService.RetrieveCustomers(officeId, term);
        }
        
        [HttpGet("customer/{customerId}/search/vehicles")]
        public async Task<IEnumerable<VehicleSearchResult>> SearchVehicles(long customerId,string term)
        {
            return _officeControllerService.RetrieveVehicles(customerId, term);
        }

        [HttpPost("office/{officeId}/request")]
        public async Task<IActionResult> EditRequest(EditRequestInputModel model)
        {
            if (ModelState.IsValid)
            {
                var routeValues = new RouteValueDictionary
                {
                    {"officeId", model.OfficeId}
                };
                if (!model.RequestId.HasValue)
                {
                    var manager = await _userManager.GetUserAsync(HttpContext.User);
                    var result = _officeControllerService.CreateRequest(model, manager.Id);
                    routeValues.Add("requestId", result.Item1.Id);
                    if (result.Item2) return RedirectToAction("EditDiagnostic", routeValues);
                };

                routeValues.Add("requestId", model.RequestId.Value);
                _officeControllerService.UpdateRequest(model);
                return RedirectToAction("EditDiagnostic", routeValues);
            }
            
            ModelState.AddModelError("failed",
                "Возникли ошибки при заполнении формы. Проверьте, пожалуйста, правильность и полноту заполнения.");
            return View(model);
        }

        [HttpGet]
        public IActionResult Vehicles(long customerId)
        {
            var vehicles = _vehicleRepository.FindAll().Where(x => x.CustomerId == customerId);
            return View(vehicles);
        }

        [HttpGet("office/{officeId}/customer/{customerId}/vehicle/edit/{vehicleId?}")]
        public IActionResult EditVehicle(long officeId, long customerId, long? vehicleId = null, [FromQuery]string returnUrl="")
        {
            if (vehicleId.HasValue)
            {
                var vehicle = _vehicleRepository.FindById(vehicleId.Value);
                //TODO не распознается адрес
                var vm = _mapper.Map<VehicleViewModel>(vehicle);
                return View(vm);
            }

            var model = new VehicleViewModel
            {
                Id = vehicleId,
                CustomerId = customerId,
                OfficeId = officeId
            };

            ViewBag.ReturnUrl = returnUrl;
            return View(model);
        }

        [HttpPost("office/{officeId}/customer/{customerId}/vehicle/edit")]
        public async Task<IActionResult> EditVehicle(EditVehicleInputModel model, [FromForm]string returnUrl="")
        {
            if (ModelState.IsValid) 
            {
                if (model.Id == default)

Server/Views/Office/Edit.cshtml
@model Application.InputModels.EditOfficeInputModel;
@{
    ViewBag.Title = "Создание записи о офисе";
    Layout = "_Layout";
}
<h2>Happy to have you on board!</h2>
<form method="POST" action="@Url.Content("~/office/edit")">
    <fieldset style="margin-top: 50px">
        <legend>Редактирование офиса</legend>
        <div class="col-xs-7">

            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.AddressId)

            <div class="input-group input-group-lg">
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {placeholder = Html.DisplayNameFor(m => m.Name)}})
                @Html.ValidationMessageFor(model => model.Name)
            </div>

            <div class="input-group input-group-lg">
                @Html.EditorFor(model => model.Inn, new {htmlAttributes = new {placeholder = Html.DisplayNameFor(m => m.Inn)}})
                @Html.ValidationMessageFor(model => model.Inn)
            </div>

            <div class="input-group input-group-lg">
                @Html.EditorFor(model => model.Phone, new {htmlAttributes = new {placeholder = Html.DisplayNameFor(m => m.Phone)}})
                @Html.ValidationMessageFor(model => model.Phone)
            </div>

            <div class="input-group input-group-lg">
                @Html.EditorFor(model => model.City, new {htmlAttributes = new {placeholder = Html.DisplayNameFor(m => m.City)}})
                @Html.ValidationMessageFor(model => model.City)
            </div>

            <div class="input-group input-group-lg">
                @Html.EditorFor(model => model.Street, new {htmlAttributes = new {placeholder = Html.DisplayNameFor(m => m.Street)}})
                @Html.ValidationMessageFor(model => model.Street)
            </div>

            <div class="input-group input-group-lg">
                @Html.EditorFor(model => model.Home, new {htmlAttributes = new {placeholder = Html.DisplayNameFor(m => m.Home)}})
                @Html.ValidationMessageFor(model => model.Home)
            </div>

            <div class="input-group input-group-lg">
                @Html.EditorFor(model => model.Flat, new {htmlAttributes = new {placeholder = Html.DisplayNameFor(m => m.Flat)}})
                @Html.ValidationMessageFor(model => model.Flat)
            </div>

            <div class="input-group">
                <div style="padding-top: 10px;">
                    <div class="col-xs-9">
                        <span class="error" style="font-size:1.2em;">@Html.ValidationMessage("failed")</span>
                    </div>
                    <div class="col-xs-3">
                        <input type="submit" class="btn btn-lg btn-primary" value="Сохранить"/>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>
</form>

Server/Views/Office/EditCustomer.cshtml
@model Application.ViewModels.CustomerViewModel;
@{
    ViewBag.Title = "Создание записи о клиенте";
    Layout = "_Layout";
}

<h2>Happy to have you on board!</h2>
<form method="POST" action="@Url.Content($"~/office/{Model?.OfficeId}/customer/edit")">
    <fieldset style="margin-top: 50px">
        <legend>Редактирование клиента</legend>
        <div class="col-xs-7">

            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.AddressId)
            @Html.HiddenFor(x => x.OfficeId)

            <div class="input-group input-group-lg">
                @Html.EditorFor(model => model.LastName, new {htmlAttributes = new {placeholder = Html.DisplayNameFor(m => m.LastName)}})
                @Html.ValidationMessageFor(model => model.LastName)
            </div>

            <div class="input-group input-group-lg">
                @Html.EditorFor(model => model.FirstName, new {htmlAttributes = new {placeholder = Html.DisplayNameFor(m => m.FirstName)}})
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>

            <div class="input-group input-group-lg">
                @Html.EditorFor(model => model.Phone, new {htmlAttributes = new {placeholder = Html.DisplayNameFor(m => m.Phone)}})
                @Html.ValidationMessageFor(model => model.Phone)
            </div>

            <div class="input-group input-group-lg">
                @Html.EditorFor(model => model.Email, new {htmlAttributes = new {placeholder = Html.DisplayNameFor(m => m.Email)}})
                @Html.ValidationMessageFor(model => model.Email)
            </div>

            <div class="input-group input-group-lg">
                @Html.EditorFor(model => model.City, new {htmlAttributes = new {placeholder = Html.DisplayNameFor(m => m.City)}})
                @Html.ValidationMessageFor(model => model.City)
            </div>

            <div class="input-group input-group-lg">
                @Html.EditorFor(model => model.Street, new {htmlAttributes = new {placeholder = Html.DisplayNameFor(m => m.Street)}})
                @Html.ValidationMessageFor(model => model.Street)
            </div>

            <div class="input-group input-group-lg">
                @Html.EditorFor(model => model.Home, new {htmlAttributes = new {placeholder = Html.DisplayNameFor(m => m.Home)}})
                @Html.ValidationMessageFor(model => model.Home)
            </div>

            <div class="input-group input-group-lg">
                @Html.EditorFor(model => model.Flat, new {htmlAttributes = new {placeholder = Html.DisplayNameFor(m => m.Flat)}})
                @Html.ValidationMessageFor(model => model.Flat)
            </div>

            <div class="input-group">
                <div style="padding-top: 10px;">
                    <div class="col-xs-9">
                        <span class="error" style="font-size:1.2em;">@Html.ValidationMessage("failed")</span>
                    </div>
                    <div class="col-xs-3">
                        <input type="submit" class="btn btn-lg btn-primary" value="Сохранить"/>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>
</form>

Server/Views/Office/EditDiagnostic.cshtml
@model Application.ViewModels.DiagnosticViewModel;
@{
    ViewBag.Title = "Выбор вида диагностики";
    Layout = "_Layout";
}

@section Scripts
{
    <script src="~/select2/js/select2.full.min.js"></script>
    <script src="~/js/editRequestItems.js"></script>
}


@Html.ActionLink("Назад", "EditRequest", "Office", new {officeId = @Model.OfficeId, requestId = @Model.RequestId})

<form method="POST" action="@Url.Content($"~/request/{Model.RequestId}/diagnostic/edit/")">
    @Html.HiddenFor(x => x.RequestId,  new { @id = "requestId"})
    
    <div class="form-group">
        <label>Выбор диагностики</label>
        <select class="diagnostic-multiple" name="diagnosticItems" multiple="multiple">
            @for (int i = 0; i < Model.Items.Count(); i++)
            {
                <option value="@Model.Items[i].Id" selected="@(Model.SelectedDiagnosticItemIds.Contains(Model.Items[i].Id))">@Model.Items[i].DisplayName</option>
            }
        </select>
    </div>
    
    <div class="col-xs-3">
        <input type="submit" class="btn btn-lg btn-primary" value="Сохранить"/>
    </div>
</form>

Server/Views/Office/EditManager.cshtml
@model Application.InputModels.EditManagerInputModel
@{
    ViewBag.Title = "Добавление пользователя";
    Layout = "_Layout";
}

<form asp-action="Create" asp-controller="Manager">
    <div asp-validation-summary="All" class="text-danger"></div>
    
    <label for="officeId">Менеджер</label>

    @Html.HiddenFor(x => x.OfficeId)
    
    <div class="form-group">
        <label asp-for="Email" class="control-label">Email</label>
        <input type="text" asp-for="Email" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="Lastname" class="control-label">Lastname</label>
        <input type="text" asp-for="Lastname" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="Firstname" class="control-label">Firstname</label>
        <input type="text" asp-for="Firstname" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="Password" class="control-label">Пароль</label>
        <input type="password" asp-for="Password" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="Year" class="control-label">Год рождения</label>
        <input type="number" asp-for="Year" class="form-control"/>
    </div>
    <div class="form-group">
        <input type="submit" value="Добавить" class="btn btn-outline-secondary"/>
    </div>
</form>

Server/Views/Office/EditRequest.cshtml
@model Application.ViewModels.RequestInitializationViewModel;
@{
    ViewBag.Title = "Редактирование заявки";
    Layout = "_Layout";
}

@section Scripts
{
    <script src="~/select2/js/select2.full.min.js"></script>
    <script src="~/js/select2.js"></script>
}

<form method="POST" action="@Url.Content($"~/office/{Model.OfficeId}/request/")">
    @Html.HiddenFor(x => x.OfficeId,  new { @id = "officeId"})
    @Html.HiddenFor(x => x.RequestId,  new { @id = "requestId"})
 
    <div class="form-group">
        <label for="customerId">Клиент</label> @Html.ActionLink("Не нашли клиента, создайте новую запись", "EditCustomer", new {officeId = @Model.OfficeId})
        <select name="customerId" class="form-control" id="customerId">
            @if (Model.CustomerId.HasValue)
            {
                <option value="@Model.CustomerId.Value">@Model.CustomerFullName</option>
            }
        </select>

        <label for="vehicleId">Автомобиль</label> <a href="#" onclick="redirectToEditVehicle()">Не нашли автомобиль клиента, создайте новую запись</a>
        <select name="vehicleId" class="form-control" id="vehicleId">
            @if (Model.VehicleId.HasValue)
            {
                <option value="@Model.VehicleId.Value">@Model.VehicleName</option>
            }
        </select>
    </div>
    
    
    <div class="col-xs-3">
        <input type="submit" class="btn btn-lg btn-primary" value="Сохранить"/>
    </div>
</form>

Server/Views/Office/EditVehicle.cshtml
@model Application.ViewModels.VehicleViewModel;
@{
    ViewBag.Title = "Регистрация автомобиля";
    Layout = "_Layout";
    var returnUrl = ViewBag.ReturnUrl;
}
<h2>Happy to have you on board!</h2>
@Html.HiddenFor(x => x.OfficeId)

<form method="POST" action="@Url.Content($"~/office/{Model?.OfficeId}/customer/{Model?.CustomerId}/vehicle/edit")">
    <fieldset style="margin-top: 50px">
        <legend>Редактирование автомобиля</legend>
        <div class="col-xs-7">

            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.CustomerId)
            @Html.HiddenFor(x => returnUrl)
            
            <div class="input-group input-group-lg">
                @Html.EditorFor(model => model.Firm, new {htmlAttributes = new {placeholder = Html.DisplayNameFor(m => m.Firm)}})
                @Html.ValidationMessageFor(model => model.Firm)
            </div>

            <div class="input-group input-group-lg">
                @Html.EditorFor(model => model.ModelName, new {htmlAttributes = new {placeholder = Html.DisplayNameFor(m => m.ModelName)}})
                @Html.ValidationMessageFor(model => model.ModelName)
            </div>
            @* *@
            <div class="input-group input-group-lg">
                @Html.EditorFor(model => model.Year, new {htmlAttributes = new {placeholder = Html.DisplayNameFor(m => m.Year)}})
                @Html.ValidationMessageFor(model => model.Year)
            </div>

            <div class="input-group input-group-lg">
                @Html.TextBoxFor(model => model.EngineVolume), new {htmlAttributes = new {placeholder = Html.DisplayNameFor(m => m.EngineVolume)}})
                 @Html.ValidationMessageFor(model => model.EngineVolume)
            </div>

            <select asp-for="HandSide" asp-items="Html.GetEnumSelectList<DomainModel.Vehicles.HandSide>()">
            </select>

            <div class="input-group">
                <div style="padding-top: 10px;">
                    <div class="col-xs-9">
                        <span class="error" style="font-size:1.2em;">@Html.ValidationMessage("failed")</span>
                    </div>
                    <div class="col-xs-3">
                        <input type="submit" class="btn btn-lg btn-primary" value="Сохранить"/>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>
</form>