Server/Models/Customer/CreateViewModel.cs
namespace AutoRepair.Models.Customer
{
    public class CreateViewModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public AddressViewModel Address { get; set; }
    }

    public class AddressViewModel
    {
        public string City { get; set; }
        public string Street { get; set; }
        public string Home { get; set; }
        public string Flat { get; set; }
    }
}

Server/Controllers/ManagerController.cs
using System.Threading.Tasks;
using Application.InputModels;
using DomainModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AutoRepair.Controllers
{
    public class ManagerController : Controller
    {
        private readonly UserManager<User> _userManager;

        public ManagerController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }
        // GET
        
        
        [HttpPost]
        public async Task<IActionResult> Create(EditManagerInputModel model)
        {
            if (ModelState.IsValid)
            {
                var manager = new Manager {Email = model.Email, Firstname = model.Firstname, Lastname = model.Lastname, UserName = model.Email, Year = model.Year, OfficeId = model.OfficeId.Value};
                var result = await _userManager.CreateAsync(manager, model.Password);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                foreach (var error in result.Errors) ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }
        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            var model = new EditUserInputModel {Id = user.Id, Email = user.Email, Year = user.Year};
            return View(model);
        }
    }
}

Server/Controllers/UsersController.cs
using System.Linq;
using System.Threading.Tasks;
using Application.InputModels;
using DomainModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AutoRepair.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserManager<User> _userManager;

        public UsersController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View(_userManager.Users.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserInputModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User {Email = model.Email, UserName = model.Email, Year = model.Year};
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                foreach (var error in result.Errors) ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            var model = new EditUserInputModel {Id = user.Id, Email = user.Email, Year = user.Year};
            return View(model);
        }
    }
}

Server/Views/Manager/Create.cshtml
@model Application.InputModels.EditManagerInputModel
@{
    ViewBag.Title = "Добавление пользователя";
    Layout = "_Layout";
}

@section Scripts
{
    <script src="~/select2/js/select2.full.min.js"></script>
    <script src="~/js/createManager.js"></script>
}

<form asp-action="Create" asp-controller="Manager">
    <div asp-validation-summary="All" class="text-danger"></div>
    
    <label for="officeId">Клиент</label>
    
     <div class="form-group">
            <label for="officeId">Клиент</label>
             <select name="officeId" class="form-control" id="officeId">
                 @if (Model?.OfficeId != null)
                 {
                     <option value="@Model.OfficeId.Value"></option>
                 }
             </select>
     </div>
     
    <div class="form-group">
        <label asp-for="Email" class="control-label">Email</label>
        <input type="text" asp-for="Email" class="form-control"/>
    </div>
    <div class="form-group">
            <label asp-for="Lastname" class="control-label">Lastname</label>
        <input type="text" asp-for="Lastname" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="Firstname" class="control-label">Firstname</label>
        <input type="text" asp-for="Firstname" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="Password" class="control-label">Пароль</label>
        <input type="password" asp-for="Password" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="Year" class="control-label">Год рождения</label>
        <input type="number" asp-for="Year" class="form-control"/>
    </div>
    <div class="form-group">
        <input type="submit" value="Добавить" class="btn btn-outline-secondary"/>
    </div>
</form>

Server/Views/Manager/Edit.cshtml
@model Application.InputModels.EditUserInputModel
@{
    ViewBag.Title = "Редактирование пользователя";
}
<form asp-action="Edit" asp-controller="Users">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <input type="hidden" asp-for="Id"/>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label">Email</label>
        <input type="text" asp-for="Email" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="Year" class="control-label">Год рождения</label>
        <input type="number" asp-for="Year" class="form-control"/>
    </div>
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-outline-secondary"/>
    </div>
</form>

Server/Views/Manager/Index.cshtml
@model IEnumerable<DomainModel.Manager>
@{
    ViewBag.Title = "Список пользователей";
}

<a asp-action="Create">Добавить пользователя</a>

<table class="table">
    <tr>
        <th>Email</th><th>Год</th><th></th>
    </tr>
    @foreach (var user in Model)
    {
        <tr>
            <td>@user.Email</td>
            <td>@user.Year</td>
            <td>
                <form asp-action="Delete" asp-route-id="@user.Id" method="post">
                    <a class="btn btn-sm btn-primary" asp-action="Edit" asp-route-id="@user.Id">Изменить</a>
                    <button type="submit" class="btn btn-sm btn-danger">
                        Удалить
                    </button>
                </form>
            </td>
        </tr>
    }
</table>